#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --depth 1 --recursive --init

system_type=$(uname -s)
if [ "$system_type" = "Darwin" ]; then
    ./.mac-config

    # install homebrew if it's missing
    if ! command -v brew >/dev/null 2>&1; then
        echo "Installing homebrew"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    if [ -f "$HOME/.Brewfile" ]; then
        echo "Updating homebrew bundle"
        brew bundle --global

        grep -q rstudio .Brewfile && .bin/clean-rstudio
        grep -q quarto .Brewfile && .bin/clean-quarto
        grep -q positron .Brewfile && .bin/clean-positron
    fi

    [ ! -f ~/Library/Fonts/FiraCode*.ttf ] && open https://github.com/tonsky/FiraCode/releases
    open https://lib.stat.cmu.edu/R/CRAN/
fi
