#!/usr/bin/env bash
set -e

ln -f -s ~/.positron/extensions/posit.air-vscode-*/bundled/bin/air ~/.local/bin/


pushd /Applications/Positron.app/Contents/

strip-intel() {
    lipo -remove x86_64 "$1" -output "$1"
}

# Clean up Electron
pushd "Frameworks/Electron Framework.framework/Versions/Current/Resources"
for lproj in *.lproj
do
    [ "$lproj" != "en.lproj" ] && rm -r "$lproj"
done
popd

# Clean up main app and quarto
cd Resources
for lproj in *.lproj
do
    [ "$lproj" != "en.lproj" ] && rm -r "$lproj"
done

cd app
rm -rf quarto
ln -s /Applications/quarto quarto

# cd extensions
# pushd positron-assistant/resources/copilot
# rm -rf x64
# popd
# cd bootstrap
# rm -rf x64
# cd ..

defaults write -app Positron ApplePressAndHoldEnabled -bool false

popd
